### ISSUE TITLE
Feature Request Summary - Meets Expectations

### ISSUE THREAD

**Issue by jlag34** [Lulubells/Jammming#4]
Overall, nice job on your feature request. Your feature was something new and something that would benefit the app. Great job including all of the necessary subjects in your request. In your technical design, I think you did a good good explaining what needed to be done. Although there was no code provided, the instructions were fairly clear on what needed to be done. In your caveats area, you talked about having to update state twice. That isn't a problem in React but I think you implementation can be tweaked slightly. Once you add the track to your new array from state, I would then try to remove it from the search results. Once, you created both of your new arrays (new tracklist with the track added and new search results with the track removed) then update state with `setState`. Lastly, I would not rely on CSS to hide tracks that are already in your playlist. All in all, great job with this one and I hope you enjoyed the course!

**Comment by Lulubells** [comment]
@jlag34 Thank you for the advice! I loved this course and I can't wait to continue my learning.
